### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by osbota01** [ds4owd-001/md-02-assignments-osbota01#1]
@larnsce @mianzg @sskorik01 Completed but I have a few questions: 

1. When I use the shortcut to add a pipe operator (Ctrl + Shift + M), I am getting something that looks like "%>%" instead of "|>". I think Lars mentioned this during today's session, but I can't remember the issue.

2. At some point during the homework, running code chunks stopped working. When I hit 'Run Current Chunk', I saw nothing new in my console and no new plots showed up in the plots pane. However, when I hit Render, I could still see all my new plots in the other window. I tried reopening Posit Cloud but had the same problem. Any ideas what's going on? Thanks!

**Comment by larnsce** [comment]
Thank you, @osbota01. 

>  When I use the shortcut to add a pipe operator (Ctrl + Shift + M), I am getting something that looks like "%>%" instead of "|>". I think Lars mentioned this during today's session, but I can't remember the issue.

I only demonstrated how to change to the native pipe operator `|>` when I did the "my turn" live coding. I had planned to demonstrate to you during the "our turn" session how to change the pipe operator, but forgot. Thanks for noting it down here.

I have started writing a guide now: https://ds4owd-001.github.io/website/guide/

> I tried reopening Posit Cloud but had the same problem. Any ideas what's going on? Thanks!

I opened your project on Posit Cloud and noticed the issue. It happened because your code chunks were actually indented under bullet points. When you want to add a new code chunk, make sure that it's not sitting on a bullet point, but on an individual new line. You can do so by hitting the Enter key on your keyboard until you reach below the last bullet point and your cursor jumps back to the beginning of the line. I fixed it in your code now, please re-open the md-02-assignments-osbota01 and once again, commit & push to GitHub.

Your current issue is visible in the source file at this place:

https://github.com/ds4owd-001/md-02-assignments-osbota01/blob/b622a92433f9620800090abc7bf44e9fdabb2edc/md-02a-data-visualization.qmd#L152

**Comment by larnsce** [comment]
You can close the issue once you have commited and pushed the recent changes.

**Comment by osbota01** [comment]
Thanks so much for troubleshooting! I just committed and pushed the updated version. Closing the issue now.
